<?php

declare(strict_types=1);
//[STAMP] c191ac0986f2902bab006307f7c9875b

namespace _generated;

/**
 * This class was automatically generated by build task
 * You should not change it manually as it will be overwritten on next build.
 *
 * @codingStandardsIgnoreFile
 */
trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
